#!/bin/bash

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -m|--message)
    MESSAGE="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

echo ""
echo "--------------------------------------------------------------------------------"
echo "Deploying app with the following commit message:"
echo "'${MESSAGE}'"
echo "--------------------------------------------------------------------------------"

yarn build
git add .
git commit -m "${MESSAGE}"
git push
ssh thomas@104.236.66.208 "cd tunes; git pull; exit"
